name: Build VSIX

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Package VSIX
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: Install deps (if any)
        run: npm ci || npm i

      - name: Package
        run: vsce package
        # Produces something like minimal-themes-1.0.1.vsix

      - name: Upload artifact (always)
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: "*.vsix"

  release:
    name: Create GitHub Release (on tag)
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix
          path: ./dist

      - name: Get VSIX filename
        id: vsix
        run: echo "file=$(ls dist/*.vsix | head -n1)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.vsix.outputs.file }}
          generate_release_notes: true
